name: CVOverheid
main: nl.colablikje12.cvoh.CVOverheid
version: 2.0
author: colablikje12
softdepend: [SuperVanish]
permissions:
  cv.overheid.inkoop:
    default: false
  cv.overheid.gemeente:
    default: false
  cv.overheid.bouwbedrijf:
    default: false
  cv.overheid.tech:
    default: false
  cv.overheid.secret:
    default: false
  cv.overheid.belastingdienst:
    default: false
  cv.overheid.politie:
    default: false